### ISSUE TITLE
Asset Manager voting_event's "items": is "" instead of [] when set to Type: "All Items"

### ISSUE THREAD

**Issue by elv-todd** [eluv-io/elv-asset-manager#36]
_no rush responding just wanted to file_

### summary

we were unmarshaling the voting_events into objects that expected "items" to be an array of string.  but when the Asset Manager has a voting_events entry that is set to Type: "All Items", entry's "items": is "" instead of what we might expect as a [] instead.

not sure if this is something CF metadata accessors should expect and handle this as-is.  will require some special casing.

### sample

for example, on demov3 we had starflicks voting event 

"id": "GzjyZrtNiy8RLvP1iMyBGT"
"title": "Favorite Movie or Show"

which now has Type: Specified Items" and items set, and parses fine:
```
{
              "description": "",
              "end_date": "2025-03-09T00:00:00-08:00",
              "exclusive": false,
              "id": "GzjyZrtNiy8RLvP1iMyBGT",
              "items": [
                "Hn5JScGHxJDrCG2VVK485v",
                "2jsbJpwTFv86P8Zyn8FZag",
                "5Zb7yp4sHjkjr3UZChy4z7"
              ],
              "start_date": "2023-03-09T00:00:00-08:00",
              "title": "Favorite Movie or Show",
              "type": "specified"
            }
```

but before, we left "Type" set to "All Items", which resulted in the items array being "" instead of "[]"...

before:
```
{
            {
              "description": "",
              "end_date": "2025-03-09T00:00:00-08:00",
              "exclusive": false,
              "id": "GzjyZrtNiy8RLvP1iMyBGT",
              "items": "",
              "start_date": "2023-03-09T00:00:00-08:00",
              "title": "Favorite Movie or Show",
              "type": "all"
            }  

```

**Comment by elv-kevin** [comment]
this is a quirk of how the asset manager handles hidden values that are never shown. since I don't have time to really dig into this, I've just changed the default type of voting events to 'specified', so the items list always will be shown (and populated with []) by default when the event is first created
